version: '3'
services:
  postgres:
    container_name: postgres-container
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: app_name
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password